### ISSUE TITLE
Setting up mirror with aptly errors due to temporary work directory 

### ISSUE THREAD

**Issue by sailendhran** [rabbitmq/erlang-debian-package#22]
Tried to setup a mirror from the details provided in https://www.rabbitmq.com/install-debian.html#apt-bintray-erlang to install rabbitmq and erlang on ubuntu 18.04 (bionic) using aptly.

```
$ aptly mirror update erlang
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/InRelease...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/Release...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/Release.gpg...
gpgv: Signature made Thu 23 Jul 2020 04:40:17 AM NZST using RSA key ID 6026DFCA
gpgv: Good signature from "RabbitMQ Release Signing Key <info@rabbitmq.com>"
Downloading & parsing package files...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/elixir/binary-amd64/Packages.bz2...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/elixir/binary-i386/Packages.bz2...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/erlang/binary-amd64/Packages.bz2...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/erlang/binary-i386/Packages.bz2...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/work_1592838775903/bionic/elixir/binary-amd64/Packages.bz2...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/work_1592838775903/bionic/elixir/binary-amd64/Packages.gz...
Downloading https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/work_1592838775903/bionic/elixir/binary-amd64/Packages...
ERROR: unable to update: HTTP code 404 while fetching https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/work_1592838775903/bionic/elixir/binary-amd64/Packages
```

Is this directory .work_1592838775903 required under https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/ ?

**Comment by michaelklishin** [comment]
We do not maintain `dl.bintray.com`. Bintray's apt repository reindexing is a black box to us as much as it is a black box to you.

We have previously seen plenty of evidence that the indexing process is not atomic, not predictable in terms of how long it takes, and sometimes an indexed repo goes "semi-indexed" without any new packages deployed (my guess is that it happens when Bintray deploys a certain kind of update). As such, mirroring it cannot be expected to be predictable.

This package is open source and only has minor deviations from the upstream Debian Erlang packages. A more predictable  approach might be building the packages and uploading them to your mirror. Or mirroring the Debian Testing, which currently provides [Erlang 23.0.3](https://packages.debian.org/search?keywords=erlang-base&searchon=names&suite=testing&section=all), the latest patch release as of at least yesterday.

**Comment by michaelklishin** [comment]
I have expanded up my comment to offer some observations on Bintray's reindexing process.
