### ISSUE TITLE
Build packages for aarch64 (arm64 in Debian)

### ISSUE THREAD

**Issue by hrw** [rabbitmq/erlang-debian-package#24]
OpenStack depends on RabbitMQ which depends on Erlang.

You provide packages for both RabbitMQ and Erlang but only for x86-64 (amd64) architecture. For aarch64 I am trying to keep up with backporting Erlang from Debian 'testing' but from time to time get hit by lack of updated package.

Can you build also for aarch64?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(

**Comment by michaelklishin** [comment]
Err, DIscussions are not enabled for this repo.

I don't think our team has more resources to dedicate to this package. Due to the upcoming Bintray shutdown we had to emergency evacuate it to a soon-to-be announced PPA and Cloudsmith.io. There are no plans to put more time into these packages besides maintenance necessary to keep up with the upstream releases (and maybe upstream Debian changes).

If the OpenStack community needs ARM 64 versions of this packages, they should take the source and run with it. This is open source software after all.

**Comment by michaelklishin** [comment]
FWIW [Docker community images](https://github.com/docker-library/rabbitmq) of RabbitMQ provide an ARM 64 version. I don't know if this option is realistic for OpenStack.

Ubuntu PPAs [supposedly support ARM 64 builds](https://askubuntu.com/questions/371339/how-to-create-ppa-packages-for-arm-or-powerpc-in-launchpad) if a package opts-in, we will see if this is still the case (the post is from 2016 and the docs it links to are very very brief).

**Comment by hrw** [comment]
Thanks for honest answer @michaelklishin. Will keep own builds.

**Comment by michaelklishin** [comment]
I have [requested](https://answers.launchpad.net/launchpad/+question/696183) ARM64 builds for [this new PPA](https://launchpad.net/~rabbitmq/+archive/ubuntu/rabbitmq-erlang) (it only provides Erlang 23 plus a few versions we need for internal testing of upgrades).

If this works for you, you are welcome to switch. We plan to maintain that PPA as one of Bintray replacements. Unfortunately I cannot guarantee that our ARM64 build request will be approved or if Launchpad will continue supporting ARM64 at all in the future.
