### ISSUE TITLE
Q: Add Support for Ubuntu 23.10 in ppa?

### ISSUE THREAD

**Issue by Loedn** [rabbitmq/erlang-debian-package#37]
### Is your feature request related to a problem? Please describe.

Hi all, trying to install the erlang ppa on ubuntu 23.10, official distro package is stuck at elixir 1.14 would love to jump on the 1.15 wagon.. 
![image](https://github.com/rabbitmq/erlang-debian-package/assets/20359974/f4475de4-d8fd-4ba5-aec4-0fe466331ab1)
I've been getting this error and doing some digging is due to the fact that there's no official release for 23.xx

### Describe the solution you'd like

Is it possible to support 23.xx or does the release/packaging schedule only follow LTS releases?

**Comment by michaelklishin** [comment]
The package should work just fine on 23.10. Just specify `jammy` or `lunar` or something reasonably recent for distribution name.

**Comment by michaelklishin** [comment]
You confuse "support for a distribution" with indexing for a distribution. The most recent release of Erlang 26 came out two weeks before Ubuntu 23.10 did, so it makes sense that it was not indexed for 23.10 even by Launchpad.

On Launchpad, we only index for LTS releases because indexing for *every* distribution would waste resources and Launchpad is a free service that has already bumped our resource allowance beyond what they offer by default.
